proyectoFinal: main.o menu.o creaArbol.o addAll.o clear.o contains.o remove.o cambioNodo.o verColeccion.o
	gcc -o proyectoFinal main.o menu.o creaArbol.o addAll.o clear.o contains.o remove.o cambioNodo.o verColeccion.o

main.o: main.c
	gcc -c main.c

menu.o: menu.c
	gcc -c menu.c

creaArbol.o:  creaArbol.c
	gcc -c  creaArbol.c

addAll.o: addAll.c
	gcc -c addAll.c

clear.o: clear.c
	gcc -c clear.c

contains.o: contains.c
	gcc -c contains.c

remove.o: remove.c
	gcc -c remove.c

cambioNodo.o:  cambioNodo.c
	gcc -c  cambioNodo.c

verColeccion.o: verColeccion.c
	gcc -c verColeccion.c

rm: .*